### PR TITLE
Feature/scss

### PR DESCRIPTION
**Pull request by Lucasktrindade**
Hi there, 

I've talked to you earlier and i already done SCSS Version for GRIDE. It's a great project, i don't put node sass at package json, i use gulp to compile. And i don't know how to do tests, if you can explain to me, i would be thankfully.

And this was such a great idea!

### CODE REVIEW

**Comment by guuibayer** [comment]
Hi @Lucasktrindade!
Seriously, how cool you have implemented the scss version, the structure is cool as the stylus, just a doubt, the files are with the prefix _, can we leave without?

The @thiamsantos helped us implementing the tests, can we create a stylus folder and another scss with their respective tests?

**Comment by Lucasktrindade** [comment]
We use this prefix to files that will not be compiled alone, and if someone need to use just go there and import. If you want, i change @guuibayer .

**Comment by thiamsantos** [comment]
Thanks @Lucasktrindade!!! Good work. 
Just a doubt, why you added idea folders to the gitignore?

**Comment by Lucasktrindade** [comment]
Because i use Webstorm, and when i open the project there, it's created, it's kind a configuration file for my IDE.

**Comment by thiamsantos** [comment]
I understood @Lucasktrindade. So I think now we make the merge. What you think @guuibayer? And tomorrow I can write the tests.

**Comment by guuibayer** [comment]
Beauty, but if we remove the prefixes could there be any problem?

**Comment by Lucasktrindade** [comment]
There's no problem, i'll change the prefixes.

**Pull request merged**
